name: Run Spectral and Upload SARIF
on:
  push:
    branches: [ main ]
    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  run_spectral_and_upload_sarif:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install and run Spectral CI
        uses: spectralops/spectral-github-action@v3
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --engines iac,oss  --sarif --ok
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Upload SARIF file
        uses: actions/upload-artifact@v2
        with:
          name: spectral-results
          path: output.sarif
